# Generated by Django 3.2 on 2021-05-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0002_auto_20210503_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
