# Generated by Django 3.2 on 2021-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='capicity',
            field=models.PositiveIntegerField(),
        ),
    ]
