# Generated by Django 3.2 on 2021-04-28 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0003_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date published')),
                ('order_address', models.CharField(max_length=5000)),
                ('quantity', models.IntegerField()),
                ('deliver_status', models.BooleanField(default=False)),
                ('food_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RMS.food')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
