# Generated by Django 3.2 on 2021-05-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
