# Generated by Django 3.2 on 2021-05-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0004_alter_table_capicity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='food',
            new_name='table',
        ),
    ]
