# Generated by Django 3.2 on 2021-04-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0005_food_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='profile_pic',
            new_name='food_pic',
        ),
    ]
