# Generated by Django 3.2 on 2021-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0005_auto_20210503_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBack',
            new_name='Review',
        ),
    ]
