# Generated by Django 3.2 on 2021-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0006_booking_on_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='On_Off',
        ),
        migrations.AddField(
            model_name='booking',
            name='Conform',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
