# Generated by Django 3.2 on 2021-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0006_rename_feedback_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_Avg_Rating',
            field=models.FloatField(null=True),
        ),
    ]
