# Generated by Django 3.2 on 2021-05-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0008_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RMS.food'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
