# Generated by Django 3.2 on 2021-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0008_alter_booking_conform'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Table_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Tables/'),
        ),
    ]
