# Generated by Django 3.2 on 2021-05-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0009_table_table_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_time',
            field=models.DateTimeField(null=True),
        ),
    ]
