# Generated by Django 3.2 on 2021-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0009_auto_20210503_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
