# Generated by Django 3.2 on 2021-05-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0010_food_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Discount',
            new_name='Discount_In_Percentage',
        ),
    ]
