# Generated by Django 3.2 on 2021-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0010_booking_booking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=5000)),
                ('Email', models.CharField(max_length=6000)),
                ('message', models.CharField(max_length=7000)),
            ],
        ),
    ]
