# Generated by Django 3.2 on 2021-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0011_rename_discount_food_discount_in_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pincode',
            field=models.CharField(max_length=50, null=True, verbose_name='Pincode'),
        ),
    ]
