# Generated by Django 3.2 on 2021-05-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
