# Generated by Django 3.2 on 2021-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0012_myuser_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='state'),
        ),
    ]
