# Generated by Django 3.2 on 2021-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0013_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.CharField(max_length=6000, null=True),
        ),
    ]
