# Generated by Django 3.2 on 2021-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0013_auto_20210518_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
