# Generated by Django 3.2 on 2021-05-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0014_auto_20210519_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='penilty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('discount', models.PositiveIntegerField()),
                ('tex', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('food', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RMS.food')),
                ('order_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RMS.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
