# Generated by Django 3.2 on 2021-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0015_orders_check_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
