# Generated by Django 3.2 on 2021-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0015_auto_20210519_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='penilty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
