# Generated by Django 3.2 on 2021-05-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0016_bill_penilty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
