# Generated by Django 3.2 on 2021-05-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0017_auto_20210520_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
