# Generated by Django 3.2 on 2021-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0018_orders_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='penilty',
        ),
        migrations.AddField(
            model_name='myuser',
            name='penilty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
