# Generated by Django 3.2 on 2021-05-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0019_auto_20210520_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='penilty',
        ),
    ]
