# Generated by Django 3.2 on 2021-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0020_remove_bill_penilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='penilty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
