# Generated by Django 3.2 on 2021-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0021_bill_penilty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.PositiveIntegerField(blank=0, null=True),
        ),
    ]
