# Generated by Django 3.2 on 2021-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0022_alter_orders_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
