# Generated by Django 3.2 on 2021-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0023_alter_orders_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
