# Generated by Django 3.2 on 2021-05-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0024_auto_20210522_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='penilty',
            field=models.FloatField(null=True),
        ),
    ]
